### ISSUE TITLE
Increase Sign Ups on Brigade Site

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/civictech#2]
#### Description

As a funnel to participation in the civic tech movement, we have direct control over the Brigade website. Lets optimize it for sign ups.
#### tasks
- [ ] Get current analytics of sign ups
- [ ] Get analytics of v3 version
- [ ] Do user testing and a/b testing to increase sign ups.
