### ISSUE TITLE
Event Attendance

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/civictech#7]
#### Description

Another great metric for participation is attendance. We should build an easy tool for the Brigades to track attendance.
#### Tasks
- [ ] Build attendance tool
- [ ] Connect it to the PeopleDB
- [ ] Also let people get results directly
